source 'https://rubygems.org'
gem 'rails', '4.1.8'
gem "compass-rails"
gem 'font-awesome-rails'
gem 'carrierwave',             '0.10.0'
gem 'mini_magick',             '3.8.0'
gem 'fog',                     '1.23.0'
gem 'bcrypt',               '3.1.7'
gem 'faker',                '1.4.2'
gem 'bootstrap-sass',       '3.2.0.0'
gem 'will_paginate',           '3.0.7'
gem 'bootstrap-will_paginate', '0.0.10'
gem 'mysql2'
gem 'rails_12factor', '0.0.2'
gem 'tilt','1.4.1'
gem 'sass-rails', '4.0.3'
gem 'uglifier', '>= 2.5.3'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.2.3'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'sprockets', '2.11.0'
gem 'pry'